name: Build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt update
        apt install -y cmake git build-essential autoconf texinfo bison flex pkg-config wget bash
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: psp2cldr_sdk-linux
        path: build/*.tar.bz2
