name: Build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt update
        apt install -y cmake git build-essential autoconf texinfo bison flex pkg-config wget bash python3
        ln -sf python3 /usr/bin/python
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: psp2cldr_sdk-linux
        path: build/*.tar.bz2

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: psp2cldr_sdk-linux

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          title: "Automated Release ${{ github.run_number }}"
          prerelease: false
          files: |
            *.tar.bz2
